# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuffCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_flags', models.IntegerField()),
                ('yellow_flags', models.IntegerField()),
                ('red_jail', models.IntegerField()),
                ('yellow_jail', models.IntegerField()),
                ('red_yukko', models.IntegerField()),
                ('yellow_yukko', models.IntegerField()),
                ('red_alarm', models.IntegerField()),
                ('yellow_alarm', models.IntegerField()),
                ('red_gotcha', models.IntegerField()),
                ('yellow_gotcha', models.IntegerField()),
                ('red_recharge', models.IntegerField()),
                ('yellow_recharge', models.IntegerField()),
                ('red_wands', models.IntegerField()),
                ('green_wands', models.IntegerField()),
                ('blue_wands', models.IntegerField()),
                ('white_wands', models.IntegerField()),
                ('red_belts', models.IntegerField()),
                ('green_belts', models.IntegerField()),
                ('blue_belts', models.IntegerField()),
                ('white_belts', models.IntegerField()),
                ('red_potions', models.IntegerField()),
                ('green_potions', models.IntegerField()),
                ('blue_potions', models.IntegerField()),
                ('white_potions', models.IntegerField()),
            ],
        ),
    ]
