# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171029_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffcount',
            name='red_hats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stuffcount',
            name='yellow_hats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
