# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180415_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Event assignments',
            },
        ),
        migrations.CreateModel(
            name='GameAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(unique=True)),
                ('head', models.CharField(blank=True, max_length=255)),
                ('dh_jail', models.CharField(blank=True, max_length=255)),
                ('dh_roam_1', models.CharField(blank=True, max_length=255)),
                ('dh_roam_2', models.CharField(blank=True, max_length=255)),
                ('weh_jail', models.CharField(blank=True, max_length=255)),
                ('weh_roam_1', models.CharField(blank=True, max_length=255)),
                ('weh_roam_2', models.CharField(blank=True, max_length=255)),
                ('on_call', models.CharField(blank=True, max_length=255)),
                ('playing', models.CharField(blank=True, max_length=255)),
                ('exec', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EventAssignments')),
            ],
            options={
                'verbose_name_plural': 'Game assignments',
                'ordering': ['game_number'],
            },
        ),
    ]
