# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eventassignments_gameassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventassignments',
            name='semester',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
