# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_eventassignments_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventassignments',
            name='semester',
            field=models.CharField(default='Unknown semester', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='dh_jail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='dh_roam_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='dh_roam_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='exec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='head',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='on_call',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='playing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='weh_jail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='weh_roam_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameassignments',
            name='weh_roam_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
