# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-08 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191007_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameassignments',
            old_name='exe',
            new_name='exec_people',
        ),
    ]
